### ISSUE TITLE
Does it works with rails 4.2 ?

### ISSUE THREAD

**Issue by bricesanchez** [reed/actionview-encoded_mail_to#6] opened 2015-03-02 16:10 UTC
I've added your gem in my Gemfile and added the option `encode:` to my mail_to but nothing happens, do you know why ?

```ruby
= mail_to team.email, team.name, class: 'email', encode: 'hex'
# => <a class="email" encode="hex" href="mailto:test@test.com">Mr. Test</a>
```
I use Refinery CMS 3.0 and Rails 4.2.

**Comment by IvRRimum** [comment] 2015-03-04 17:10
No it does not. :-1:

**Comment by reed** [comment] 2015-03-04 22:13
Using a blank Rails 4.2 app, it worked just fine.  Using a Refinery 3.0-generated app using Rails 4.2, it also worked fine.

![image](https://cloud.githubusercontent.com/assets/672142/6494677/24e37b18-c289-11e4-8103-5c06fb4d21aa.png)

So I'm not sure why you're having an issue.

**Comment by IvRRimum** [comment] 2015-03-06 10:19
Just cloned the gem, changed rails version to 4.2 and ran tests, most of them fail.

**Comment by reed** [comment] 2015-03-06 10:57
After updating to 4.2, I had to add `require 'action_view/helpers/output_safety_helper'` to the top of the test file to get the tests to run.  Once I did that, all the tests passed.  If you're seeing something different, show me.

**Comment by bricesanchez** [comment] 2015-03-20 15:07
It works in my refinerycms engine only if i add this gem in the Gemfile of my app.

**Comment by atstockland** [comment] 2015-04-10 16:06
Not working for me in Rails 4.2, either.

**Comment by ollie** [comment] 2015-04-16 07:26
Somehow does work for me on Rails 4.2.1, just added in Gemfile, no hacking required. Huh.

**Comment by reed** [comment] 2015-04-16 20:26
I'd love to help you guys, but I can't fix an issue I can't reproduce.

**Comment by newmetl** [comment] 2015-04-28 19:39
My Rails app is a bit older (4.0.5) and I have the following behavior:

```
= mail_to 'contact@email.com', 'contact@email.com', body: 'message goes here', subject: 'Please get in touch with me', encode: 'javascript'
```
works but breaks the `&` between body and subject.
```
<a href="mailto:contact@email.com?body=body&amp;amp;subject=Please%20get%20in%20touch%20with%20me">contact@9elements.com</a>
```

Passing a block also doesn't work at all.

```
= mail_to 'some@email.com', encode: 'javascript' do
  text text
```
returns
```
<a encode="javascript" href="mailto:some@email.com">text text</a>
```

Hope this helps.

**Comment by reed** [comment] 2015-04-28 22:48
@newmetl This is a separate problem.  Can you open a new issue?

**Comment by newmetl** [comment] 2015-04-30 12:44
Created new issues.

**Comment by reed** [comment] 2015-05-02 23:50
Released a new version fixing @newmetl's issues.  TravisCI ran using Rails 4.2.1 and all the tests passed, so I'm closing this issue.

**Closed by reed** 2015-05-02 23:50 UTC

**Comment by newmetl** [comment] 2015-05-03 08:41
Awesome, thank's a lot!
